### ISSUE TITLE
hitting pad causes a javascript error

### ISSUE THREAD

**Issue by Moonshot128** [ejj28/mididrumhero#16]
i know someone already had this problem but i tried restarting my pc like they said and nothing happened. it only happens when i hit a pad that has been registered. before that i can just hit it and it’ll say on the monitor that i hit a pad. when i do add it as a new drum pad, then it starts giving me the javascript error.
![7CC0568E-C687-42C3-93CC-66EB2B35A6BC](https://user-images.githubusercontent.com/47840972/104852982-76cdd500-58c3-11eb-9979-10bb0d965eef.png)

**Comment by ejj28** [comment]
Close MidiDrumHero, then open the program 'Configure vJoy' on your PC and click 'Reset All', then try again.
