### ISSUE TITLE
"Error: ENOENT: No such file or directory" encountered during program startup

### ISSUE THREAD

**Issue by TheNathannator** [ejj28/mididrumhero#2]
**Description:**
After installing, this error message shows up when starting the program:
```
Uncaught Exception:
Error: ENOENT: no such file or directory, open
'C:\Users\[user]\AppData\Roaming\mididrumhero\storage\config.json'
   at Object.openSync (fs.js:440:3)
   at Object.func (electron/js2c/asar.js:140:31)
   at Object.func [as openSync] (electron/js2c/asar.js:140:31)
   at Object.readFileSync (fs.js:342:35)
   at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
   at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
   at getMidiConfig
(C:\Users\[user]\AppData\Local\Programs\mididrumhero\resources\app.asar\index.js:114:20)
   at Object.<anonymous>
(C:\Users\[user]\AppData\Local\Programs\mididrumhero\resources\app.asar\index.js:12:18)
   at Module._compile (internal/modules/cjs/loader.js:968:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
```
(Copied verbatim from the error message)

The `Appdata\Roaming\mididrumhero` folder contains only the `Dictionaries` folder.
The `Appdata\Local\Programs\mididrumhero` folder appears to be fine.

![Error message](https://user-images.githubusercontent.com/29052821/78633445-e9068900-785e-11ea-9149-a70c4c608db2.png)
![Roaming directory](https://user-images.githubusercontent.com/29052821/78633751-9083bb80-785f-11ea-8927-e8942ad55e58.png)

**Comment by skully662** [comment]
I have the same issue

**Comment by skully662** [comment]
same error here any clues to what it might be

**Comment by TheNathannator** [comment]
My best guess is either the installer isn't installing everything correctly (specifically, it's not extracting some things that it needs), or certain files that should be created on first run aren't being made.

**Comment by towner-10** [comment]
Just published a new release with an extra check for creating the config.json file. The original check didn't use async for some reason. This is kind of a band-aid fix, would be greatly appreciated if you guys could test to see if it now works.

Thanks for helping us out!

**Comment by TheNathannator** [comment]
The program starts correctly now. Thanks for fixing it!
