### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Marcuss202** [ejj28/mididrumhero#28]
![image_2022-06-06_153938877](https://user-images.githubusercontent.com/74297172/172162244-6e036ab9-2065-4222-97a6-88f65da91786.png)

yesterday there was no problem. Now its showing an error every time i hit something on my drum set. Can you help me?

**Comment by ejj28** [comment]
Hi there,
MidiDrumHero has been superseded by Clone Hero's built in Midi support. I suggest you discontinue the use of MidiDrumHero and use that instead.
