### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by ejj28** [ejj28/mididrumhero#3]
Add support for midi keyboards for playing Keys in Clone Hero

**Comment by TheNathannator** [comment]
I've been using my RB3 keyboard, and it works great so far. The only thing that impacts playing is that the input is cut off briefly after pushing the key, but I imagine that making a separate mode for keys that doesn't do that would make playing with keys work perfectly.

**Comment by ejj28** [comment]
Implemented in https://github.com/ejj28/mididrumhero/commit/1820e159b4cf7b1cff8966a5057be543bafba6ba
