### ISSUE TITLE
Button number can be set to extreme values

### ISSUE THREAD

**Issue by TheNathannator** [ejj28/mididrumhero#6]
I don't know if this is intended behavior, but button values can be set ***really*** high. They can also go into the negatives, which doesn't sound like it would be good.

These aren't embedding, but they demonstrate the problem:
[Large positive number GIF](https://i.imgur.com/cQpicMm.gifv)
[Large negative number GIF](https://i.imgur.com/Nq7WfUb.gifv)

**Comment by ejj28** [comment]
Thanks for pointing this out, we'll be working on it and it should be fixed in another prerelease or the final release of 2.0.0

**Comment by towner-10** [comment]
Fixed in 3d635ea6b7b5022adf05a14f0a1642c149646db6.
