### ISSUE TITLE
Support for sustained guitar inputs

### ISSUE THREAD

**Issue by MineClashTV** [ejj28/mididrumhero#7]
I know the title of this project is "midi _drum_ hero" yet I would still think having the ability to use a MIDI device as a guitar would be awesome. While it theoretically is possible to play like this, all inputs are really short (which makes sense when you're just going for drums), but makes playing everything else than drums very difficult.

**Comment by ejj28** [comment]
I am thinking about adding a keyboard mode in the future that'll basically just leave the note on until the midi device sends a note-off signal, which wasn't really feasible for drums as usually the note-off signal comes too quickly for it the note to even register. At the moment though, Pro Drums support is higher priority, but I do expect to add keyboard and other device support eventually, unless the game devs beat me to it and add midi support themselves, which will happen eventually I'm sure

**Comment by ejj28** [comment]
Implemented in https://github.com/ejj28/mididrumhero/commit/1820e159b4cf7b1cff8966a5057be543bafba6ba
